version: '3'

services:
  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./cs224n:/code/
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser

  run-tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./cs224n:/code/
    command: /bin/bash
