[tool.poetry]
name = "cs224n"
version = "0.1.0"
description = "Notes for CS224n"
authors = ["bekiekb1"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
nltk = "^3.8.1"
pandas = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
